### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by haru-moja** [haru-moja/protospace-31642#2]
自身のProtoSpaceのURL：https://protospace-31642.herokuapp.com/
本番環境(Heroku)のURL：https://git.heroku.com/protospace-31642.git

**Comment by MasaakiTanabashi** [comment]
大木さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◎投稿されたプロトタイプの投稿者名から投稿者のユーザーページへ遷移できません。
<img width="1243" alt="ProtoSpace" src="https://user-images.githubusercontent.com/64255541/97958784-48c31380-1df1-11eb-96ec-dfbcaab7646f.png">

◎ユーザーページの投稿されたプロトタイプの投稿者名をクリックすると、トップページへ遷移してしまう。
<img width="1320" alt="ProtoSpace" src="https://user-images.githubusercontent.com/64255541/97959014-d141b400-1df1-11eb-9702-55ba69d89586.png">


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by MasaakiTanabashi** [comment]
大木さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
